import type { Metadata } from "next";
import { Geist, Geist_Mono, Jost, Noto_Sans_Devanagari } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import { LanguageProvider } from "@/components/providers/LanguageProvider";
import { MusicPlayerLayout } from "@/components/providers/MusicPlayerLayout";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const jost = Jost({
	variable: "--font-jost",
	subsets: ["latin"],
});

const notoDevanagari = Noto_Sans_Devanagari({
	variable: "--font-devanagari",
	subsets: ["devanagari", "latin"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Dharmlok",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} ${notoDevanagari.variable} antialiased`}
			>
				<NextTopLoader
					color="#ea580c"
					height={3}
					showSpinner={false}
					easing="ease"
					speed={300}
				/>
				<AuthProvider>
					<LanguageProvider>
						<MusicPlayerLayout>
							{children}
						</MusicPlayerLayout>
						<Toaster position="top-right" richColors closeButton />
					</LanguageProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
