import type { Metadata } from "next";
import { Geist, Geist_Mono, Jost } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const jost = Jost({
	variable: "--font-jost",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} antialiased`}
			>
				<NextTopLoader
					color="#ea580c"
					height={3}
					showSpinner={false}
					easing="ease"
					speed={300}
				/>
				<AuthProvider>
					{children}
					<Toaster position="top-right" richColors closeButton />
				</AuthProvider>
			</body>
		</html>
	);
}
